config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :menu_categories
  resources :menu_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/', to: 'menu_items#index'

  get '/sales', to: 'menu_items#reports'
  
  post '/tambah-order', to: 'orders#tambahOrder'
  post '/tambah-menu-item', to: 'menu_items#tambahMenuItem'
  post '/tambah-menu-category', to: 'menu_categories#tambahMenuCategory'
  post '/tambah-item-pesanan', to: 'order_details#tambahItemPesanan'

  patch '/update-menu-item/:id', to: 'menu_items#updateMenuItem'
  patch '/konfirmasi-pesanan', to: 'orders#konfirmasiPesanan'
  patch '/konfirmasi-pembatalan-pesanan', to: 'orders#konfirmasiPembatalanPesanan'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  has_many :menu_item
end

app/controllers/menu_categories_controller.rb
class MenuCategoriesController < ApplicationController
  before_action :set_menu_category, only: %i[ show edit update destroy ]
  protect_from_forgery with: :null_session, only: [:tambahMenuItem]
  
  def tambahMenuCategory
    @menu_category = MenuCategory.new
    @menu_category.name = params[:name]
    @menu_category.description = params[:description]
    @menu_category.save!
    redirect_to '/menu_items'
  end
  
  # GET /menu_categories or /menu_categories.json
  def index
    @menu_categories = MenuCategory.all
  end

  # GET /menu_categories/1 or /menu_categories/1.json
  def show
  end

  # GET /menu_categories/new
  def new
    @menu_category = MenuCategory.new
  end

  # GET /menu_categories/1/edit
  def edit
  end

  # POST /menu_categories or /menu_categories.json
  def create
    @menu_category = MenuCategory.new(menu_category_params)

    respond_to do |format|
      if @menu_category.save
        format.html { redirect_to redirect_to '/menu_items', notice: "Menu category was successfully created." }
        format.json { render :show, status: :created, location: @menu_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_categories/1 or /menu_categories/1.json
  def update
    respond_to do |format|
      if @menu_category.update(menu_category_params)
        format.html { redirect_to '/menu_items', notice: "Menu category was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_categories/1 or /menu_categories/1.json
  def destroy
    @menu_category = MenuCategory.find_by(id: params[:id])
    puts "8"
    @menu_category.destroy

    respond_to do |format|
      format.html { redirect_to '/menu_items', notice: "Menu category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_category
      @menu_category = MenuCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_category_params
      params.require(:menu_category).permit(:name, :description)
    end
end

app/helpers/menu_categories_helper.rb
module MenuCategoriesHelper
end

app/views/menu_categories/_form.html.erb
<%= form_with(model: menu_category) do |form| %>
  <% if menu_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu_category.errors.count, "error") %> prohibited this menu_category from being saved:</h2>

      <ul>
        <% menu_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_categories/_menu_category.html.erb
<div id="<%= dom_id menu_category %>">
  <p>
    <strong>Name:</strong>
    <%= menu_category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu_category.description %>
  </p>

</div>

app/views/menu_categories/edit.html.erb
<div class="container" >
<h1>Edit Kategori</h1>

<%= render "form", menu_category: @menu_category %>

<br>

<div>
  <%= link_to "Kembali ke Dashboard", menu_items_path %>
</div>
  </div>

app/views/menu_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menu categories</h1>

<div id="menu_categories">
  <% @menu_categories.each do |menu_category| %>
    <%= render menu_category %>
    <p>
      <%= link_to "Show this menu category", menu_category %>
    </p>
  <% end %>
</div>

<%= link_to "New menu category", new_menu_category_path %>

app/views/menu_categories/new.html.erb
<h1>New menu category</h1>

<%= render "form", menu_category: @menu_category %>

<br>

<div>
  <%= link_to "Back to menu categories", menu_categories_path %>
</div>

app/views/menu_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu_category %>

<div>
  <%= link_to "Edit this menu category", edit_menu_category_path(@menu_category) %> |
  <%= link_to "Back to menu categories", menu_categories_path %>

  <%= button_to "Destroy this menu category", @menu_category, method: :delete %>
</div>