config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :menu_categories
  resources :menu_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/', to: 'menu_items#index'

  get '/sales', to: 'menu_items#reports'
  
  post '/tambah-order', to: 'orders#tambahOrder'
  post '/tambah-menu-item', to: 'menu_items#tambahMenuItem'
  post '/tambah-menu-category', to: 'menu_categories#tambahMenuCategory'
  post '/tambah-item-pesanan', to: 'order_details#tambahItemPesanan'

  patch '/update-menu-item/:id', to: 'menu_items#updateMenuItem'
  patch '/konfirmasi-pesanan', to: 'orders#konfirmasiPesanan'
  patch '/konfirmasi-pembatalan-pesanan', to: 'orders#konfirmasiPembatalanPesanan'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, foreign_key: "order_id"
  belongs_to :menu_item, foreign_key: "menu_item_id"
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_order_detail, only: %i[ show edit update destroy ]
  protect_from_forgery with: :null_session, only: [:tambahItemPesanan]
  def tambahItemPesanan
    @order_detail = OrderDetail.new
    @order_detail.menu_item_id= params[:menu_item_id]
    @order_detail.order_id = params[:order_id]
    @order_detail.portion_size = params[:portion_size]
    @order_detail.total_portion_price = params[:portion_size].to_f * params[:menu_item_price].to_f
    @order_detail.save!
    redirect_to order_url(params[:order_id])

    @listOfOrderItems = OrderDetail.where(order_id: params[:order_id])
    @totalPrice = 0
    @listOfOrderItems.each do |orderItem|
      @totalPrice += orderItem.total_portion_price.to_f
    end
    @order = Order.find_by(id: params[:order_id])
    @order.update(total_price: @totalPrice)
  end
  
  # GET /order_details or /order_details.json
  def index
    @order_details = OrderDetail.all
  end

  # GET /order_details/1 or /order_details/1.json
  def show
  end

  # GET /order_details/new
  def new
    @order_detail = OrderDetail.new
  end

  # GET /order_details/1/edit
  def edit
  end

  # POST /order_details or /order_details.json
  def create
    @order_detail = OrderDetail.new(order_detail_params)

    respond_to do |format|
      if @order_detail.save
        format.html { redirect_to order_url(params[:order_id]), notice: "Order detail was successfully created." }
        format.json { render :show, status: :created, location: @order_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_details/1 or /order_details/1.json
  def update
    respond_to do |format|
      if @order_detail.update(order_detail_params)
        format.html { redirect_to order_url(params[:order_id]), notice: "Order detail was successfully updated." }
        format.json { render :show, status: :ok, location: @order_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_details/1 or /order_details/1.json
  def destroy
    @order_detail.destroy

    @listOfOrderItems = OrderDetail.where(order_id: params[:order_id])
    @totalPrice = 0
    @listOfOrderItems.each do |orderItem|
      @totalPrice += orderItem.total_portion_price.to_f
    end
    @order = Order.find_by(id: params[:order_id])
    @order.update(total_price: @totalPrice)

    respond_to do |format|
      format.html { redirect_to order_url(params[:order_id]), notice: "Order detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_detail
      @order_detail = OrderDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_detail_params
      params.require(:order_detail).permit(:menu_item_id, :order_id, :portion_size, :total_portion_price)
    end
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/order_details/_form.html.erb
<%= form_with(model: order_detail) do |form| %>
  <% if order_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order_detail.errors.count, "error") %> prohibited this order_detail from being saved:</h2>

      <ul>
        <% order_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :menu_item_id, style: "display: block" %>
    <%= form.number_field :menu_item_id %>
  </div>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.number_field :order_id %>
  </div>

  <div>
    <%= form.label :portion_size, style: "display: block" %>
    <%= form.number_field :portion_size %>
  </div>

  <div>
    <%= form.label :total_portion_price, style: "display: block" %>
    <%= form.text_field :total_portion_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/order_details/_order_detail.html.erb
<div id="<%= dom_id order_detail %>">
  <p>
    <strong>Menu item:</strong>
    <%= order_detail.menu_item_id %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= order_detail.order_id %>
  </p>

  <p>
    <strong>Portion size:</strong>
    <%= order_detail.portion_size %>
  </p>

  <p>
    <strong>Total portion price:</strong>
    <%= order_detail.total_portion_price %>
  </p>

</div>

app/views/order_details/edit.html.erb
<h1>Editing order detail</h1>

<%= render "form", order_detail: @order_detail %>

<br>

<div>
  <%= link_to "Show this order detail", @order_detail %> |
  <%= link_to "Back to order details", order_details_path %>
</div>

app/views/order_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Order details</h1>

<div id="order_details">
  <% @order_details.each do |order_detail| %>
    <%= render order_detail %>
    <p>
      <%= link_to "Show this order detail", order_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New order detail", new_order_detail_path %>

app/views/order_details/new.html.erb
<h1>New order detail</h1>

<%= render "form", order_detail: @order_detail %>

<br>

<div>
  <%= link_to "Back to order details", order_details_path %>
</div>

app/views/order_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_detail %>

<div>
  <%= link_to "Edit this order detail", edit_order_detail_path(@order_detail) %> |
  <%= link_to "Back to order details", order_details_path %>

  <%= button_to "Destroy this order detail", @order_detail, method: :delete %>
</div>