config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :menu_categories
  resources :menu_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/', to: 'menu_items#index'

  get '/sales', to: 'menu_items#reports'
  
  post '/tambah-order', to: 'orders#tambahOrder'
  post '/tambah-menu-item', to: 'menu_items#tambahMenuItem'
  post '/tambah-menu-category', to: 'menu_categories#tambahMenuCategory'
  post '/tambah-item-pesanan', to: 'order_details#tambahItemPesanan'

  patch '/update-menu-item/:id', to: 'menu_items#updateMenuItem'
  patch '/konfirmasi-pesanan', to: 'orders#konfirmasiPesanan'
  patch '/konfirmasi-pembatalan-pesanan', to: 'orders#konfirmasiPembatalanPesanan'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_category, foreign_key: "menu_category_id"
  has_many :order_details, :dependent => :delete_all
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[ show edit update destroy]
  protect_from_forgery with: :null_session, only: [:tambahMenuItem, :updateMenuItem]
  
  def tambahMenuItem
    @menu_item = MenuItem.new
    @menu_item.name = params[:name]
    @menu_item.description = params[:description]
    @menu_item.price = params[:price]
    @menu_item.menu_category_id = params[:menu_category_id]
    @menu_item.save!
    redirect_to '/menu_items'
  end

  def updateMenuItem
    @menu_item2 = MenuItem.find_by(id: params[:id])
    @menu_item2.update(name: params[:name], description: params[:description], price: params[:price], menu_category_id: params[:menu_category_id])

    redirect_to '/menu_items'
  end

  def reports
    case params[:searchBy]
    when 'datePick'
      if params[:datePick]
        @datePick = params[:datePick]
      else
        @datePick = Date.today
      end
      @tableTitle = "Report for invoices made on " + @datePick.to_s
      @orders = Order.where(status: "PAID").where("created_at LIKE ?", "%" + @datePick.to_s + "%")
      
    when 'emailPick'
      @tableTitle = "Report for invoices made by " + params[:emailPick].to_s
      @orders = Order.where(status: "PAID").where("email LIKE ?", "%" + params[:emailPick].to_s + "%")
    when 'highestPick'
      @tableTitle = "Report for invoices with total expenses higher than Rp." + params[:highestPick].to_s
      @orders = Order.where(status: "PAID").where("total_price > ?",  params[:highestPick].to_f )
    when 'dateRangePick'
      @tableTitle = "Report for invoices made between " + params[:dateRangePickSince].to_s + " until " + params[:dateRangePickUntil].to_s
      @orders = Order.where(status: "PAID").where("created_at BETWEEN ? AND ?",  params[:dateRangePickSince].to_s, params[:dateRangePickUntil].to_s )
    else
      @orders = Order.all
    end

    @totalEarnings = 0
    @orders.each do |orderItem|
      @totalEarnings += orderItem.total_price.to_f
    end

  end
  
  # GET /menu_items or /menu_items.json
  def index
    @menu_items = MenuItem.all
    @menu_category_items = MenuCategory.all
    @order_items = Order.all
  end

  # GET /menu_items/1 or /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
    @menu_category_items = MenuCategory.all
  end

  # GET /menu_items/1/edit
  def edit
    @menu_category_items = MenuCategory.all
  end

  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)
    @menu_category_items = MenuCategory.all

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to '/menu_items', notice: "Menu item was successfully created." }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to '/menu_items', notice: "Menu item was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    @menu_item.destroy

    respond_to do |format|
      format.html { redirect_to '/menu_items', notice: "Menu item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :description, :price, :menu_category_id)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item) do |form| %>
  <% if menu_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :menu_category_id, style: "display: block" %>
    <%= form.text_field :menu_category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<div id="<%= dom_id menu_item %>">
  <p>
    <strong>Name:</strong>
    <%= menu_item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu_item.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= menu_item.price %>
  </p>

  <p>
    <strong>Categoryid:</strong>
    <%= menu_item.menu_category_id %>
  </p>

</div>

app/views/menu_items/edit.html.erb
<div class="container" >
<h1>Edit Menu Item</h1>

<form action="/update-menu-item/<%= @menu_item.id %>" method="post">
  <%= csrf_meta_tags %>
  <input name="_method" type="hidden" value="patch" />
  <label for="name">Name :</label><br>
  <input type="text" id="name" name="name" value='<%= @menu_item.name %>' class="form-control"><br>
  <label for="description">Description :</label><br>
  <textarea id="description" name="description" class="form-control"><%= @menu_item.description %></textarea><br>
  <label for="price">Price /portion :</label><br>
  <input type="text" id="price" name="price" value='<%= @menu_item.price %>' class="form-control"><br>
  <label for="menu_category_id">Category :</label><br>
  <select name="menu_category_id" id="menu_category_id" class="form-control">
  <% @menu_category_items.each do |menu_category| %>
  <% if menu_category.id == @menu_item.menu_category_id %>
  <option selected value=<%= menu_category.id %> ><%= menu_category.name %></option>
<% else %>
  <option value=<%= menu_category.id %> ><%= menu_category.name %></option>
  <% end %>
  <% end %>
  </select><br>

  <input type="submit" value="Submit">
</form>

<br>

<div>
  <%= link_to "Kembali ke Dashboard", menu_items_path %>
</div>
  </div>

app/views/menu_items/index.html.erb
<div class="container" >

  <div class="row">

    
  <div class="mt-4 alert alert-success" role="alert">
  Hello, owner. Here's your dashboard. Check the list of unconfirmed invoices below. Once you've confirmed the payment, you can set them confirmed in their respective details page. If you're seeing this from desktop, then the report button, list of menus, and list of categories shall be on the right side.
  </div>
    
  <div class="col-md-8">
  <!-- Mulai Bagian Daftar Pesanan -->
  <div id="menu_category_items">
  <h3>List of Orders</h3>

    <!-- Mulai Form Pembuatan Menu Baru -->
  <div class="card mt-2">
  <div class="card-header">Got some new orders? Enter the customer's email below..</div>
  <div class="card-body">
  <form action="/tambah-order" method="post">
  <%= csrf_meta_tags %>
  <label for="email">Enter the customer's email:</label><br>
  <input type="email" class="form-control" id="email" name="email" >
  <span>The new customer's email will be listed in the table below. Go to it's details page to add menu items.</span>
  <input type="submit" class="form-control btn btn-primary" value="Confirm New Order">
  </form>
  </div>
  </div>
  <!-- Selesai Form Pembuatan Menu Baru -->
  <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Customer's email</th>
      <th scope="col">Total order costs</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @order_items.each do |order| %>
    <tr>
    <td><%= order.email %></td>
    <td><%= number_to_currency(order.total_price, unit: "Rp.", format: "%u %n") %></td>
    <% if order.status == 'PAID' %>
    <td><span class="btn btn-primary"><%= order.status %></span></td>
    <% elsif order.status == 'CANCELED' %>
    <td><span class="btn btn-danger"><%= order.status %></span></td>
    <% else %>
    <td><span class="btn btn-success"><%= order.status %></span></td>
    <% end %>
    <td><%= link_to "See Details", order_url( :id => order.id ), class: "btn btn-outline-success" %>
    <%= button_to "Delete this order", order_url(order.id), class: "btn btn-outline-danger mt-2", method: :delete %>
        
    </td>
    </tr>
  <% end %>
  </tbody>
  </table>
    
  </div>
  <!-- Selesai Bagian Daftar Pesanan -->
  </div>
  

  <div class="col-md-4 mb-2" style="border-left:1px solid gray;">

  <!-- Mulai Bagian Daftar Menu -->

  <div id="reports">
    <h3>Reports</h3>
    <%= link_to "Click here to see overall reports of your sales", '/sales', class: "btn btn-primary w-100" %>
  </div>
    
  <div id="menu_items">
  <h3>List of menu items</h3>
    <% @menu_items.each do |menu_item| %>
    <div class="card shadow mt-2" >
    <div class="card-body">
    <h5 class="card-title"><%= menu_item.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= menu_item.menu_category.name %></h6>
    <h4>Rp.<%= menu_item.price %></h4>
    <p class="card-text"><%= menu_item.description %></p>
    <button class="btn btn-outline-success "><strong><%= number_to_currency(menu_item.price,  unit: "Rp.", format: "%u %n") %></strong></button>
    <%= link_to "Edit Menu", edit_menu_item_path(menu_item.id), class: "btn btn-outline-primary " %>
    <%= button_to "Delete Menu", menu_item_path(menu_item.id), class: "btn btn-outline-danger mt-2", method: :delete,params: { id: menu_item.id } %>
  </div>
  </div>
  <% end %>

  <!-- Mulai Form Pembuatan Menu Baru -->
  <div class="card mt-2">
  <div class="card-header">Input New Menu Item</div>
  <div class="card-body">
  <form action="/tambah-menu-item" method="post">
  <%= csrf_meta_tags %>
  <label for="name">Name of new menu:</label><br>
  <input type="text" class="form-control" id="name" name="name" >
  <label for="description">Description :</label><br>
  <textarea class="form-control" id="description" name="description" ></textarea>
  <label for="price">Price per portion: (Rp. )</label><br>
  <input type="number" min="0.01" class="form-control" id="price" name="price" >
  <label for="menu_category_id">Menu's category :</label><br>
  <select name="menu_category_id" id="menu_category_id" class="form-control">
  <% @menu_category_items.each do |menu_category| %>
  <option value=<%= menu_category.id %> ><%= menu_category.name %></option>
  <% end %>
  </select><br>
  <input type="submit" class="form-control btn btn-primary" value="Confirm new menu">
  </form>
  </div>
  </div>
  <!-- Selesai Form Pembuatan Menu Baru --> 
    
  </div>
    
  <!-- Selesai Bagian Daftar Menu -->
    
  <!-- Mulai Bagian Daftar Kategori Menu -->
  <div id="menu_category_items" class="mt-2" >
  <h3>List of menu categories</h3>
  <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Category</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @menu_category_items.each do |menu_category| %>
    <tr>
    <td><%= menu_category.name %></td>
    <td>
    <%= link_to "Edit Category", edit_menu_category_path(menu_category.id), class: "btn btn-outline-primary " %>
    <%= button_to "Delete Category", menu_category_path(menu_category.id), class: "btn btn-outline-danger mt-2", method: :delete %>
    </td>
    </tr>
  <% end %>
  </tbody>
  </table>

  <!-- Mulai Form Pembuatan Kategori Baru -->
  <div class="card mt-2 ">
  <div class="card-header">Input New Menu Category</div>
  <div class="card-body">
  <form action="/tambah-menu-category" method="post">
  <%= csrf_meta_tags %>
  <label for="name">Name of new category:</label><br>
  <input type="text" class="form-control" id="name" name="name" >
  <label for="description">Description :</label><br>
  <textarea maxlength="150" class="form-control" id="description" name="description" ></textarea><br>
  <input type="submit" class="form-control btn btn-primary" value="Confirm new category">
  </form>
  </div>
  </div>
  <!-- Selesai Form Pembuatan Kategori Baru --> 
    
  </div>
  <!-- Selesai Bagian Daftar Kategori Menu -->
  </div>
    
  </div>
</div>

app/views/menu_items/new.html.erb
<div class="container" >
<h1>Menu Item Baru</h1>
<form action="/tambah-menu-item" method="post">
  <%= csrf_meta_tags %>
  <label for="name">Nama:</label><br>
  <input type="text" id="name" name="name" ><br>
  <label for="description">Deskripsi:</label><br>
  <input type="text" id="description" name="description" ><br>
  <label for="price">Harga /porsi</label><br>
  <input type="text" id="price" name="price" ><br>
  <label for="menu_category_id">Kategori</label><br>
  <input type="text" id="menu_category_id" name="menu_category_id" ><br><br>

  <input type="submit" value="Submit">
</form>
<br>

<div>
  <%= link_to "Kembali ke Dashboard", menu_items_path %>
</div>
<div class="container" >
<h1>Menu Item Baru</h1>
<form action="/tambah-menu-item" method="post">
  <%= csrf_meta_tags %>
  <label for="name">Nama:</label><br>
  <input type="text" id="name" name="name" ><br>
  <label for="description">Deskripsi:</label><br>
  <input type="text" id="description" name="description" ><br>
  <label for="price">Harga /porsi</label><br>
  <input type="text" id="price" name="price" ><br>
  <label for="menu_category_id">Kategori</label><br>
  <input type="text" id="menu_category_id" name="menu_category_id" ><br><br>
  
  <input type="submit" value="Submit">
</form>
<br>

<div>
  <%= link_to "Kembali ke Dashboard", menu_items_path %>
</div>
</div>
</div>

app/views/menu_items/reports.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
<h3>Based on what parameter do you want the report the be displayed?</h3>

  <form action="/sales" method="get">
  <%= csrf_meta_tags %>
  <table class="table table-sm">
    <tr>
      <td>Date</td>
      <td><input class="form-control" type="date" name="datePick"></td>
      <td>
      <input type="radio"  name="searchBy" value="datePick" checked>
      <label for="html">Search by the date on which the order is made</label>
      </td>
    </tr>
    <tr>
      <td>Email</td>
      <td><input class="form-control" type="text" name="emailPick"></td>
      <td>
      <input type="radio"  name="searchBy" value="emailPick">
      <label for="html">Search by customer's email</label>
      </td>
    </tr>
    <tr>
      <td>Highest invoice expenses</td>
      <td><input class="form-control" type="number" name="highestPick"></td>
      <td>
      <input type="radio"  name="searchBy" value="highestPick">
      <label for="html">Search invoices with expenses higher than defined</label>
      </td>
    </tr>
  <tr>
      <td>Date range</td>
      <td>Since :<input class="form-control" type="date" name="dateRangePickSince">
          Until :
      <input class="form-control" type="date" name="dateRangePickUntil"></td>
      <td>
      <input type="radio"  name="searchBy" value="dateRangePick">
      <label for="html">Search invoices made between the defined timespan</label>
      </td>
    </tr>
    <tr>
      <td colspan=3><input class="btn btn-primary w-100" type="submit" value="Display report" ></td>
    </tr>
  </table>
  </form>

  <h4><%= @tableTitle %></h4>
  <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Customer's email</th>
      <th scope="col">Total order costs</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
    <td><%= order.email %></td>
    <td><%= number_to_currency(order.total_price,  unit: "Rp.", format: "%u %n") %></td>
    <% if order.status == 'PAID' %>
    <td><span class="btn btn-primary"><%= order.status %></span></td>
    <% else %>
    <td><span class="btn btn-danger"><%= order.status %></span></td>
    <% end %>
    </tr>
  <% end %>
    <tr>
      <td colspan=3 style="text-align:right;">
        Total Earnings : <%= number_to_currency(@totalEarnings,  unit: "Rp.", format: "%u %n") %>
      </td>
    </tr>
  </tbody>
  </table>
  
  <%= link_to "Back to Dashboard", menu_items_path %>
  
</div>

app/views/menu_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu_item %>

<div>
  <%= link_to "Edit this menu item", edit_menu_item_path(@menu_item) %> |
  <%= link_to "Back to menu items", menu_items_path %>

  <%= button_to "Destroy this menu item", @menu_item, method: :delete %>
</div>