config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :menu_categories
  resources :menu_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/', to: 'menu_items#index'

  get '/sales', to: 'menu_items#reports'
  
  post '/tambah-order', to: 'orders#tambahOrder'
  post '/tambah-menu-item', to: 'menu_items#tambahMenuItem'
  post '/tambah-menu-category', to: 'menu_categories#tambahMenuCategory'
  post '/tambah-item-pesanan', to: 'order_details#tambahItemPesanan'

  patch '/update-menu-item/:id', to: 'menu_items#updateMenuItem'
  patch '/konfirmasi-pesanan', to: 'orders#konfirmasiPesanan'
  patch '/konfirmasi-pembatalan-pesanan', to: 'orders#konfirmasiPembatalanPesanan'
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  protect_from_forgery with: :null_session, only: [:tambahMenuItem, :updateMenuItem]
  
  def tambahOrder
    @order = Order.new
    @order.email = params[:email]
    @order.total_price = '0'
    @order.status = 'NEW'
    @order.save!
    redirect_to '/menu_items'
  end

  def konfirmasiPesanan
    @order = Order.find_by(id: params[:order_id])
    @order.update(status: 'PAID')
    redirect_to order_url(params[:order_id])
  end

  def konfirmasiPembatalanPesanan
    @order = Order.find_by(id: params[:order_id])
    @order.update(status: 'CANCELED')
    redirect_to order_url(params[:order_id])
  end

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
    @menu_items = MenuItem.all
    @order_details = OrderDetail.where(order_id: params[:id]).order(updated_at: :desc)
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to '/menu_items', notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to '/menu_items', notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to '/menu_items', notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:email, :total_price, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :total_price, style: "display: block" %>
    <%= form.text_field :total_price %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Email:</strong>
    <%= order.email %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= order.total_price %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">

      <p style="color: green"><%= notice %></p>

<%= render @order %>

  
<div>

  <form action="/konfirmasi-pesanan" method="post">
  <%= csrf_meta_tags %>
  <input name="_method" type="hidden" value="patch" />
  <input type="number"hidden  name="order_id" value="<%= @order.id %>">
  <input type="submit" class="form-control btn btn-lg btn-success" value="Confirm Invoice Payment">
  </form>

  <form action="/konfirmasi-pembatalan-pesanan" method="post">
  <%= csrf_meta_tags %>
  <input name="_method" type="hidden" value="patch" />
  <input type="number"hidden  name="order_id" value="<%= @order.id %>">
  <input type="submit" class="form-control btn btn-lg btn-danger mt-2" value="Confirm Invoice Cancellation">
  </form>
  
  <h3>List of dishes ordered</h3>
  <table class="table table-sm">
  <thead>
  <tr>
      <th scope="col">Menu's name</th>
      <th scope="col">Portion size</th>
      <th scope="col">Total portion's price</th>
      <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.menu_item.name %></td>
      <td><%= order_detail.portion_size %></td>
      <td>Rp. <%= order_detail.total_portion_price %></td>
      <td><%= button_to "Remove", order_detail_path(order_detail.id), class: "btn btn-warning mt-2", method: :delete,params: { order_id: @order.id } %></td>
    </tr>
  <% end %>
  </tbody>
  </table>
    
  <%= link_to "Back to Dashboard", menu_items_path %>
</div>
    
    </div>

    <div class="col-md-7">

        <div id="menu_items">
  <h3>List of Menus</h3>

  <div class="alert alert-success" role="alert">
  You can add the dishes to this invoice here..
  </div>
          
    <% @menu_items.each do |menu_item| %>
    <div class="card shadow mt-2" >
    <div class="card-body">
    <h5 class="card-title"><%= menu_item.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= menu_item.menu_category.name %></h6>
    <p class="card-text"><%= menu_item.description %></p>
    <button class="btn btn-outline-success "><strong>Rp.<%= menu_item.price %></strong></button>

  <form action="/tambah-item-pesanan" method="post">
  <%= csrf_meta_tags %>

  <input type="number" hidden name="order_id" value="<%= @order.id %>">
  <input type="number" hidden name="menu_item_id" value="<%= menu_item.id %>">
  <input type="number" hidden name="menu_item_price" value="<%= menu_item.price %>">

  <label for="porsi">Portion size :</label><br>
  <input type="number" class="form-control" id="portion_size" name="portion_size"  value=1 ><br>
  <input type="submit" class="form-control btn btn-primary" value="Add this dish to invoice">
  
  </form>
  </div>
  </div>
  <% end %>

    
    </div>

</div>